# mybatis 配置
mybatis:
  typeAliasesPackage: com.zt.wechat.model
  mapperLocations: classpath:mapper/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.15.71:3306/WeChat?useSSL=false
    username: zt
    password: 123


server:
  ssl:
    key-store: classpath:2055229_dyt.ink.pfx
    key-store-password: rx1czXO6
    key-store-type: PKCS12
  tomcat:
    uri-encoding: utf-8
  port: 5000
  address: 0.0.0.0